package templates

import (
	"strings"
	"testing"
)

// TestTemplateLoader_NewTemplateLoaderFromFS tests the embedded FS constructor
func TestTemplateLoader_NewTemplateLoaderFromFS(t *testing.T) {
	loader := NewTemplateLoaderFromFS(EmbeddedTemplates, "files")
	if loader == nil {
		t.Fatal("NewTemplateLoaderFromFS() returned nil")
	}
	if loader.embeddedFS == nil {
		t.Error("NewTemplateLoaderFromFS() did not set embeddedFS")
	}
	if loader.fsPrefix != "files" {
		t.Errorf("NewTemplateLoaderFromFS() fsPrefix = %q, want %q", loader.fsPrefix, "files")
	}
}

// TestTemplateLoader_LoadFromEmbeddedFS tests loading a template from embed.FS
func TestTemplateLoader_LoadFromEmbeddedFS(t *testing.T) {
	loader := NewTemplateLoaderFromFS(EmbeddedTemplates, "files")

	for _, name := range []string{"zshrc.tmpl", "aliases.tmpl", "functions.tmpl"} {
		tmpl, err := loader.LoadTemplate(name)
		if err != nil {
			t.Errorf("LoadTemplate(%q) from embedded FS error = %v", name, err)
			continue
		}
		if tmpl == nil {
			t.Errorf("LoadTemplate(%q) returned nil template", name)
		}
	}
}

// TestTemplateLoader_HasTemplate_EmbeddedFS tests HasTemplate with embedded FS
func TestTemplateLoader_HasTemplate_EmbeddedFS(t *testing.T) {
	loader := NewTemplateLoaderFromFS(EmbeddedTemplates, "files")

	if !loader.HasTemplate("zshrc.tmpl") {
		t.Error("HasTemplate(zshrc.tmpl) = false, want true")
	}
	if !loader.HasTemplate("aliases.tmpl") {
		t.Error("HasTemplate(aliases.tmpl) = false, want true")
	}
	if loader.HasTemplate("nonexistent.tmpl") {
		t.Error("HasTemplate(nonexistent.tmpl) = true, want false")
	}
}

// TestTemplateLoader_RenderZshrcFromEmbeddedFS tests rendering zshrc.tmpl from embedded FS
func TestTemplateLoader_RenderZshrcFromEmbeddedFS(t *testing.T) {
	loader := NewTemplateLoaderFromFS(EmbeddedTemplates, "files")

	data := map[string]interface{}{
		"GeneratedAt":          "2026-03-15T00:00:00Z",
		"HasOhMyZsh":           true,
		"HasPowerlevel10k":     false,
		"Plugins":              []string{"git", "docker"},
		"HasNVM":               true,
		"HasBun":               false,
		"HasSDKMAN":            false,
		"HasPNPM":              false,
		"HasDeno":              false,
		"HasHomebrew":          false,
		"HasPyenv":             false,
		"HasCargo":             false,
		"IncludeProjectConfig": false,
	}

	result, err := loader.RenderTemplate("zshrc.tmpl", data)
	if err != nil {
		t.Fatalf("RenderTemplate(zshrc.tmpl) error = %v", err)
	}

	checks := []struct{ name, want string }{
		{"header", "Generated by Homestead"},
		{"oh-my-zsh export", `export ZSH="$HOME/.oh-my-zsh"`},
		{"plugins", "plugins=(git docker)"},
		{"nvm", "NVM_DIR"},
		{"aliases source", "aliases.zsh"},
	}
	for _, c := range checks {
		if !strings.Contains(result, c.want) {
			t.Errorf("Missing %s: expected %q in rendered output", c.name, c.want)
		}
	}
}

// TestTemplateLoader_RenderAliasesFromEmbeddedFS tests rendering aliases.tmpl from embedded FS
func TestTemplateLoader_RenderAliasesFromEmbeddedFS(t *testing.T) {
	loader := NewTemplateLoaderFromFS(EmbeddedTemplates, "files")

	data := map[string]interface{}{
		"Name":        "My Config",
		"GeneratedAt": "2026-03-15T00:00:00Z",
		"Aliases": map[string]string{
			"ll": "ls -la",
			"la": "ls -A",
		},
	}

	result, err := loader.RenderTemplate("aliases.tmpl", data)
	if err != nil {
		t.Fatalf("RenderTemplate(aliases.tmpl) error = %v", err)
	}

	if !strings.Contains(result, "Aliases - Generated by Homestead") {
		t.Error("Missing aliases header")
	}
	if !strings.Contains(result, "alias ll='ls -la'") {
		t.Error("Missing ll alias")
	}
}

// TestTemplateLoader_RenderFunctionsFromEmbeddedFS tests rendering functions.tmpl from embedded FS
func TestTemplateLoader_RenderFunctionsFromEmbeddedFS(t *testing.T) {
	loader := NewTemplateLoaderFromFS(EmbeddedTemplates, "files")

	data := map[string]interface{}{
		"Name":        "My Config",
		"GeneratedAt": "2026-03-15T00:00:00Z",
		"Functions": map[string]string{
			"greet": `    echo "Hello, $1!"`,
		},
	}

	result, err := loader.RenderTemplate("functions.tmpl", data)
	if err != nil {
		t.Fatalf("RenderTemplate(functions.tmpl) error = %v", err)
	}

	if !strings.Contains(result, "Functions - Generated by Homestead") {
		t.Error("Missing functions header")
	}
	if !strings.Contains(result, "greet() {") {
		t.Error("Missing greet function")
	}
}
