package repository

import (
	"github.com/JaimeJunr/Homestead/internal/domain/entities"
	"github.com/JaimeJunr/Homestead/internal/domain/types"
)

// defaultUtilityScripts: utilitários instaláveis via scripts bash (base: LinuxToys).
func defaultUtilityScripts() []entities.Script {
	return []entities.Script{
		{ID: "util-arch-update", Name: "Arch-Update", Description: "Atualizações Arch na bandeja (Chaotic-AUR + pacotes)", Path: "scripts/utilities/archupd.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-bitwarden", Name: "Bitwarden", Description: "Gestor de senhas", Path: "scripts/utilities/fp-user/com.bitwarden.desktop.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-bottles", Name: "Bottles", Description: "Executar apps Windows com Wine", Path: "scripts/utilities/fp-user/com.usebottles.bottles.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-boxadv", Name: "Distrobox-Adv BR", Description: "Distrobox para certificado digital (advogados) + DistroShelf", Path: "scripts/utilities/boxadv.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-brave", Name: "Brave", Description: "Navegador Brave", Path: "scripts/utilities/fp-user/com.brave.Browser.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-bazaar", Name: "Bazaar", Description: "Loja de apps e jogos · instalação sistema", Path: "scripts/utilities/fp-system/io.github.kolunmi.Bazaar.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-cloudflare-warp", Name: "Cloudflare WARP", Description: "Cliente WARP (repositório oficial)", Path: "scripts/utilities/cloudflare-warp.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-cryptomator", Name: "Cryptomator", Description: "Criptografia de arquivos", Path: "scripts/utilities/fp-user/org.cryptomator.Cryptomator.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-distroshelf", Name: "DistroShelf", Description: "Podman, Distrobox e DistroShelf", Path: "scripts/utilities/distroshelf.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-easyeffects", Name: "Easy Effects", Description: "Efeitos de áudio PipeWire · instalação sistema", Path: "scripts/utilities/fp-system/com.github.wwmm.easyeffects.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-extension-manager", Name: "Extension Manager", Description: "Gestor de extensões GNOME", Path: "scripts/utilities/fp-user/com.mattjakeman.ExtensionManager.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-expressvpn", Name: "ExpressVPN", Description: "Instalador oficial ExpressVPN (Linux universal)", Path: "scripts/utilities/express-vpn.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-f3", Name: "f3", Description: "Testar cartões SD/USB contra fraude de capacidade", Path: "scripts/utilities/f3.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-flatseal", Name: "Flatseal", Description: "Permissões de apps Flatpak", Path: "scripts/utilities/fp-user/com.github.tchx84.Flatseal.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-gearlever", Name: "Gear Lever", Description: "Gestor de AppImages", Path: "scripts/utilities/fp-user/it.mijorus.gearlever.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-gnome-tweaks", Name: "GNOME Tweaks", Description: "Ajustes avançados do GNOME", Path: "scripts/utilities/gnome-tweaks.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-handbrake", Name: "HandBrake", Description: "Codificador de vídeo", Path: "scripts/utilities/fp-user/fr.handbrake.ghb.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-haguichi", Name: "Haguichi", Description: "Cliente gráfico Hamachi", Path: "scripts/utilities/fp-user/com.github.ztefn.haguichi.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-hiddify", Name: "Hiddify", Description: "Cliente Hiddify (AppImage em ~/.local)", Path: "scripts/utilities/hiddify.sh", Category: types.CategoryUtilities, RequiresSudo: false},
		{ID: "util-input-remapper", Name: "Input Remapper", Description: "Remapear teclado e mouse (input-remapper)", Path: "scripts/utilities/input-remapper.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-ivpn", Name: "IVPN", Description: "Cliente IVPN (repositório oficial)", Path: "scripts/utilities/ivpn.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-keepassxc", Name: "KeePassXC", Description: "Gestor de senhas KeePassXC", Path: "scripts/utilities/fp-user/org.keepassxc.KeePassXC.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-lact", Name: "LACT", Description: "Controle AMD GPU · instalação sistema", Path: "scripts/utilities/fp-system/io.github.ilya_zlobintsev.LACT.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-librewolf", Name: "LibreWolf", Description: "Navegador LibreWolf", Path: "scripts/utilities/fp-user/io.gitlab.librewolf-community.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-logseq", Name: "Logseq", Description: "Bloco de notas em grafos", Path: "scripts/utilities/fp-user/com.logseq.Logseq.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-mission-center", Name: "Mission Center", Description: "Monitor de sistema", Path: "scripts/utilities/fp-user/io.missioncenter.MissionCenter.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-mullvad-browser", Name: "Mullvad Browser", Description: "Navegador Mullvad", Path: "scripts/utilities/fp-user/net.mullvad.MullvadBrowser.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-mullvad-vpn", Name: "Mullvad VPN", Description: "Cliente Mullvad VPN (repositório oficial)", Path: "scripts/utilities/mullvad-vpn.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-nerd-fonts", Name: "Nerd Fonts (JetBrains)", Description: "JetBrains Mono em ~/.local/share/fonts", Path: "scripts/utilities/nerd-fonts.sh", Category: types.CategoryUtilities, RequiresSudo: false},
		{ID: "util-nordvpn", Name: "NordVPN", Description: "Cliente NordVPN (script oficial ou AUR)", Path: "scripts/utilities/nord-vpn.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-obs-studio", Name: "OBS Studio", Description: "OBS + plugin PipeWire e overrides", Path: "scripts/utilities/obs-studio.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-openlinkhub", Name: "OpenLinkHub", Description: "Periféricos Corsair (repositório / COPR / AUR)", Path: "scripts/utilities/openlinkhub.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-openrgb", Name: "OpenRGB", Description: "Iluminação RGB", Path: "scripts/utilities/fp-user/org.openrgb.OpenRGB.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-openrazer", Name: "OpenRazer", Description: "Drivers Razer + Polychromatic · instalação sistema", Path: "scripts/utilities/openrazer.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-openrazer-ublue", Name: "OpenRazer (ujust)", Description: "OpenRazer em imagens Universal Blue (ujust)", Path: "scripts/utilities/openrazer-ublue.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-oversteer", Name: "Oversteer", Description: "Ajuste de volantes", Path: "scripts/utilities/fp-user/io.github.berarma.Oversteer.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-peazip", Name: "PeaZip", Description: "Arquivador", Path: "scripts/utilities/fp-user/io.github.peazip.PeaZip.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-pika-backup", Name: "Pika Backup", Description: "Backups com Borg", Path: "scripts/utilities/fp-user/org.gnome.World.PikaBackup.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-piper", Name: "Piper", Description: "Configurar mouse (ratbagd + Flatpak sistema)", Path: "scripts/utilities/piper.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-proton-vpn", Name: "Proton VPN", Description: "Cliente Proton VPN", Path: "scripts/utilities/fp-user/com.protonvpn.www.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-qpwgraph", Name: "qpwgraph", Description: "Patchbay PipeWire", Path: "scripts/utilities/fp-user/org.rncbc.qpwgraph.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-rclone-ui", Name: "Rclone UI", Description: "Interface para rclone", Path: "scripts/utilities/fp-user/com.rcloneui.RcloneUI.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-s3drive", Name: "S3Drive", Description: "Cliente S3 / armazenamento", Path: "scripts/utilities/fp-user/io.kapsa.drive.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-sirikali", Name: "SiriKali", Description: "Volumes cifrados", Path: "scripts/utilities/fp-user/io.github.mhogomchungu.sirikali.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-solaar", Name: "Solaar", Description: "Unifying / Bolt Logitech", Path: "scripts/utilities/solaar.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-stream-controller", Name: "Stream Controller", Description: "Controles para streaming", Path: "scripts/utilities/fp-user/com.core447.StreamController.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-surfshark", Name: "Surfshark VPN", Description: "Cliente Surfshark", Path: "scripts/utilities/fp-user/com.surfshark.Surfshark.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-udev-hidraw", Name: "udev HID raw", Description: "Regra udev 0666 para USB (menu no terminal)", Path: "scripts/utilities/udev-hidraw.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-ungoogled-chromium", Name: "Ungoogled Chromium", Description: "Chromium sem Google", Path: "scripts/utilities/fp-user/io.github.ungoogled_software.ungoogled_chromium.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-vlc", Name: "VLC", Description: "Multimedia (repositórios nativos + codecs quando aplicável)", Path: "scripts/utilities/vlc.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-warehouse", Name: "Warehouse", Description: "Gestor de apps Flatpak", Path: "scripts/utilities/fp-user/io.github.flattool.Warehouse.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-waydroid", Name: "Waydroid", Description: "Android no Linux (Wayland)", Path: "scripts/utilities/waydroid.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-windscribe", Name: "Windscribe VPN", Description: "Cliente Windscribe (pacote oficial)", Path: "scripts/utilities/windscribe-vpn.sh", Category: types.CategoryUtilities, RequiresSudo: true},
		{ID: "util-wireguard", Name: "WireGuard", Description: "Ferramentas WireGuard (pacotes da distro)", Path: "scripts/utilities/wireguard.sh", Category: types.CategoryUtilities, RequiresSudo: true},
	}
}
